{% set version = "12.9.1" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart 12.9.79
    - cuda-nvrtc 12.9.86
    - cuda-opencl 12.9.19    # [linux64 or win]
    - libcublas 12.9.1.4
    - libcufft 11.4.1.4 
    - libcufile 1.14.1.1       # [linux]
    - libcurand 10.3.10.19
    - libcusolver 11.7.5.82
    - libcusparse 12.5.10.65
    - libnpp 12.4.1.87
    - libnvfatbin 12.9.82
    - libnvjitlink 12.9.86
    - libnvjpeg 12.4.0.76

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
