{% set version = "13.0.0" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart 13.0.48
    - cuda-nvrtc 13.0.48
    - cuda-opencl 13.0.39    # [linux64 or win]
    - libcublas 13.0.0.19
    - libcufft 12.0.0.15 
    - libcufile 1.15.0.42       # [linux]
    - libcurand 10.4.0.35
    - libcusolver 12.0.3.29
    - libcusparse 12.6.2.49
    - libnpp 13.0.0.50
    - libnvfatbin 13.0.39
    - libnvjitlink 13.0.39
    - libnvjpeg 13.0.0.40

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
